const ACTION_TYPES = {
  // USERS
  // Getting all
  GET_USERS_ACTION: 'GET_USERS_ACTION',
  GET_USERS_REQUEST: 'GET_USERS_REQUEST',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  GET_USERS_ERROR: 'GET_USERS_ERROR',
  // Getting
  GET_USER_ACTION: 'GET_USER_ACTION',
  GET_USER_REQUEST: 'GET_USER_REQUEST',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  GET_USER_ERROR: 'GET_USER_ERROR',
  // Creating
  POST_USER_ACTION: 'POST_USER_ACTION',
  POST_USER_REQUEST: 'POST_USER_REQUEST',
  POST_USER_SUCCESS: 'POST_USER_SUCCESS',
  POST_USER_ERROR: 'POST_USER_ERROR',
  // Updating
  PUT_USER_ACTION: 'PUT_USER_ACTION',
  PUT_USER_REQUEST: 'PUT_USER_REQUEST',
  PUT_USER_SUCCESS: 'PUT_USER_SUCCESS',
  PUT_USER_ERROR: 'PUT_USER_ERROR',
  // Deleting
  DELETE_USER_ACTION: 'DELETE_USER_ACTION',
  DELETE_USER_REQUEST: 'DELETE_USER_REQUEST',
  DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
  DELETE_USER_ERROR: 'DELETE_USER_ERROR',
  // ALBUMS
  // Getting all
  GET_ALBUMS_ACTION: 'GET_ALBUMS_ACTION',
  GET_ALBUMS_REQUEST: 'GET_ALBUMS_REQUEST',
  GET_ALBUMS_SUCCESS: 'GET_ALBUMS_SUCCESS',
  GET_ALBUMS_ERROR: 'GET_ALBUMS_ERROR',
  // Getting by userId
  GET_USER_ALBUM_ACTION: 'GET_USER_ALBUM_ACTION',
  GET_USER_ALBUM_REQUEST: 'GET_USER_ALBUM_REQUEST',
  GET_USER_ALBUM_SUCCESS: 'GET_USER_ALBUM_SUCCESS',
  GET_USER_ALBUM_ERROR: 'GET_USER_ALBUM_ERROR',
  // PHOTOS
  // Getting all
  GET_ALBUM_PHOTOS_ACTION: 'GET_ALBUM_PHOTOS_ACTION',
  GET_ALBUM_PHOTOS_REQUEST: 'GET_ALBUM_PHOTOS_REQUEST',
  GET_ALBUM_PHOTOS_SUCCESS: 'GET_ALBUM_PHOTOS_SUCCESS',
  GET_ALBUM_PHOTOS_ERROR: 'GET_ALBUM_PHOTOS_ERROR',
}

export default ACTION_TYPES;